# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'Install frontend packages'
  inputs:
    command: 'ci'
    workingDir: 'Web'
- task: DotNetCoreCLI@2
  displayName: 'Build backend'
  inputs:
    command: 'build'
    projects: '**/openspace.sln'
    arguments: '--configuration $(buildConfiguration)'
- task: Npm@1
  displayName: 'Build frontend'
  inputs:
    command: 'custom'
    workingDir: 'Web'
    customCommand: 'run publish'
- task: DotNetCoreCLI@2
  displayName: 'Publish backend'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    workingDirectory: 'Web'
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  